---

- name: Ensure apt cache is updated
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install fail2ban
  apt:
    name: fail2ban
    state: present

- name: Deploy jail.local configuration
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify: Restart fail2ban

- name: Ensure fail2ban is enabled and started
  systemd:
    name: fail2ban
    enabled: yes
    state: started